### PR TITLE
Data restore

### PR DESCRIPTION
**Pull request by RetiredWizard**
This implements a more robust DATA model that supports the RESTORE command.

The re-integration work was a mess on this one because I originally developed the code after my version of PyBasic switched to the "run in place" model. The fact that I'm passing the entire basic program as an argument tells me that I don't have the modules correct but it does seem to be working now.

One obvious alternative to passing the basic program into the basicparser module would be to add the data statement tokens onto the new basicdata structure and only pass that around. I really didn't want to do that because that meant having two copies of all the data statements and I'd still be passing that data structure around so the basic problem didn't seem to be solved.

Let me know if I'm off base on my concerns and if  anyone sees a way to restructure things to eliminate my passing problems.

### CODE REVIEW

**Comment by brickbots** [comment]
Thanks for getting this PR started!  The idea of breaking out DATA handling to its own object has a lot to recommend it, I think!

You might be able to avoid a lot of the object passing by having the Program object own the BASICData object, as it seems like it should be totally encapsulated with the Program (i.e. NEW should clear it as well, and I'm thinking that eventually we should make the NEW keyword actually destroy the program object and recreated it to give garbage collection a better shot at reclaiming memory).....

The BASICData object can be instantiated in the __init__ routine of the Program object and stored it as a proper of that object allowing its use anywhere in the program object.  You can then feed it into the __init__ call of the BasicParser object, stash it as a property and have access to it there as well without needing to pass it into any of the methods.

I think you can avoid the pgmStatements passing all together (although it will only be passing a pointer here, so not really too bad).  I *think* you are doing this so that the BASICData object can pull the data from the program listing as needed.  Although it will use bit more memory, I'd suggest the .addData method of the BASICData object not only keep track of the line numbers for DATA statements, but also record the actual data items.  

Perhaps start by converting self.__data to a dictionary keyed by line number, containing a list of the data objects.  This will be simpler to code/understand at the expense of memory overhead.  Once this is working, the representation of the program in the Program class (the list of token objects) can completely omit the actual data which will reclaim some of the memory lost by storing the data itself in the BASICData classs!  For DATA lines the program token list in Program can just hold the single token DATA for that line number, and then this can be a trigger to grab the actual data items for that line from the BASICData object it owns.  

Once this is working and PR'd, the data storage list is another place where an indexed byte array can be swapped in with a little extra effort to reduce memory consumption a lot 👍

**Comment by RetiredWizard** [comment]
Modifying .addData as you're describing is the way the "run in place" version works however with that version rather than the actual DATA statement tokens, I'm just carrying a file pointer to the line of code in flash. I didn't really mind duplicating that file pointer in both the Program class and the BASICData class but it really bothered me to duplicate the entire DATA statement token list.

I did also start the reintegration by trying to add the BASICData class to the program module, that didn't work out but I  was just adding both classes to the same module I didn't look at including the BASICData class within the Program class. I'll give that a think. The problem I was having is that both the Program class and the BASICParser class need access to the BASICData class data. This is different than how the Program data is used as BASICParser only needs access to a single statement from the Program class at a time.

**Comment by brickbots** [comment]
> Modifying .addData as you're describing is the way the "run in place" version works however with that version rather than the actual DATA statement tokens, I'm just carrying a file pointer to the line of code in flash. I didn't really mind duplicating that file pointer in both the Program class and the BASICData class but it really bothered me to duplicate the entire DATA statement token list.

Yeah, I hear you that the memory overhead of holding these data elements in both places is a drag.  If the `Program` object omits these in it's store of the program, you can get these bytes back (if you are not already cleverly running programs in place :-)    

> 
> I did also start the reintegration by trying to add the BASICData class to the program module, that didn't work out but I was just adding both classes to the same module I didn't look at including the BASICData class within the Program class. I'll give that a think. The problem I was having is that both the Program class and the BASICParser class need access to the BASICData class data. This is different than how the Program data is used as BASICParser only needs access to a single statement from the Program class at a time.

Sorry, I did a pretty bad job explaining my idea, here's a bit more detail 👍 

They can be two different class definitions, even in two separate files.  I'm just suggesting the instantiation of the `BASICData` object be done in the `Program` object rather than in the interpreter method so that you can use this object instance freely in the context of the `Program` object:

```
class Program:
    def __init__(self):
        # Dictionary to represent program
        # statements, keyed by line number
        self.__program = {}
        # Program counter
        self.__next_stmt = 0
        # Initialise return stack for subroutine returns
        # and loop returns
        self.__return_stack = []
        # Setup DATA object
        self.__data = BASICData()

```

Then later on:

``` 
    def delete_statement(self, line_number):
         """Deletes a statement from the program with
         the specified line number, if it exists

         :param line_number: The line number to be deleted

         """
         self.__data.delData(line_number)
```

When instantiating `BASICParser` in `Program.execute` you can pass in the `BASICData` object:

```
def execute(self,datastmts):
         """Execute the program"""

         self.__parser = BASICParser(self.__data)
```

Store this as an object property when initialize the `BASICParser` class:

```
def __init__(self, data_object):
        # Symbol table to hold variable names mapped
        # to values
        self.__symbol_table = {}
        # Stack on which to store operands
        # when evaluating expressions
        self.__operand_stack = []
        # List to hold contents of DATA statement
        self.__data_values = []
        # These values will be
        # initialised on a per
        # statement basis
        self.__tokenlist = []
        self.__tokenindex = None
         # Set to keep track of extant loop variables
         self. __loop_vars = set()

        self.__data = data_object
```

Which would let you access it from all the `BASICParser` methods without all the passing.

**Comment by RetiredWizard** [comment]
Okay, so I think I've got a reasonable balance. I've implemented @brickbots two suggestions (moving the BASICData instantiation and adding the tokens to the BASICData.addData method).

I also omitted the DATA values from the data structure in the Program class but left the line number and DATA token as a place holder. The place holder allowed for a relatively simple mod to the \_\_str\_\_ method to keep the list and save functionality working.

**Comment by RetiredWizard** [comment]
After the recent modifications, the BASICData class fits nicely into the program module. I'm thinking that BASICData might actually be a parent class to the Program Class (or visa versa) but I'd need to do a lot of research before I could make any real conclusions on that :)

**Comment by brickbots** [comment]
It is looking nice and tidy now, glad it worked out 👍   If you wanted to push this a bit further, you could pass the `BASICData` object into the initialization of the `BASICParser` object and then forgo passing it as a parameter to any of the `BASICParser` class methods.   

I *think* the only places it's needed in `BASICParser` is in the `__readstmt` and `__restorestmt` methods.  If the `BASICParser` took in the `BASICData` object during `__init__` and saved it as a class.parameter such a `__data` (see my last code example above for more details on this) you could remove all the passing of `datastmts` within `BASICParser` and also avoid having to pass it into `.parse` from `Program` (line 272)

In `basicparser.py` on line 489 
``` 
datastmts.restore(self.__operand_stack.pop())
```
Can become
```
self.__data.restore(self.__operand_stack.pop())
```
and similarly on line 526

**Comment by richpl** [comment]
Sorry guys, some residual conflicts above

**Pull request closed without merging**
