### PR TITLE
File io and data statements

### PR DESCRIPTION
**Pull request by RetiredWizard**
Well I still don't understand the GitHub conflict resolving process but since I had to rebuild the old PRs anyway, I went ahead and combined them.

### CODE REVIEW

**Comment by RetiredWizard** [comment]
I ported the startrek program over so that it will run under the current richpl version PyBasic. I threw together a quick python script to separate the compound lines which caused a few line number bugs, but I think I found most of those. Since PyBasic doesn't yet support the trailing delimiter to suppress the end of line carriage return some of the displays are off but I did rebuild the printouts of most of the primary control displays.

**Comment by brickbots** [comment]
Thanks for rebasing these changes and opening a new PR.  I especially appreciate the port/testing against startrek to demonstrate the compatibility!

**Comment by richpl** [comment]
Thanks for doing such a thorough job of this @RetiredWizard , particularly updating the BASIC programs. Great that you've ported and added Star Trek. I wanted to add some vintage BASIC stuff but my interpreter wasn't capable enough before!

**Comment by richpl** [comment]
@RetiredWizard, any chance you could please update the README to reflect the addition of RESTORE and the file commands? Many thanks

**Pull request merged**
