### PR TITLE
File io

### PR DESCRIPTION
**Pull request by RetiredWizard**
Adds File I/O statements

Open "filename" for [input!output!append] as \#filenum [else lineno]
input \#filenum,var1,var2,...
print \#filenum,var1,var2,...
fseek \#filenum,filepos

### CODE REVIEW

**Comment by brickbots** [comment]
It might be nice to add some of what was in testloop.bas to regression.bas as an additional test to make sure this does not get broken again in the future 👍

**Comment by brickbots** [comment]
Whoops!  I see you have this test included in the actual PR related to the loop variable bug :-)  Sorry for my confusion!

**Comment by RetiredWizard** [comment]
Updating regression.bas would have been better. I didn't do it because I didn't want to create pull conflicts. I'll go ahead and update the regression file in this pull request with the loop bug tests. Only thing is they'll fail if the loop bug pull request hasn't been merged (#30), I guess as long as that's known, it's not a problem.

**Review by brickbots — COMMENTED** [review]
Thanks @RetiredWizard !  This looks great to me 👍 

For future memory optimization, I'm thinking we can mostly ditch the `lexeme` storage in the token object (except for strings/names/ints and floats), and ultimately the list of token objects itself and store just the byte code of the token and a pointer if needed for string/name/ints and floats.  

When listing/saving the code in human readable form, calling the .lexeme property of the token object will take the token category and lookup the text for this token.  This should allow every token to be represented as one byte, rather than a memory consuming object+string.

If this ends up being one of the techniques used to save memory, you could future proof this code by making APPEND and OUTPUT first class token categories, rather than sharing the token category for input and using the textual representation (lexeme) to differentiate them:

```
 if self.__token.category not in [Token.INPUT, Token.OUTPUT, Token.APPEND]:
             raise SyntaxError('Invalid Open access mode in line ' + str(self.__line_number))

         if self.__token.category == Token.INPUT:
             accessMode = "r"
         elif self.__token.category == Token.APPEND:
             accessMode = "r+
         else:
             accessMode = "w+"
```

And then making sure to add these tokens in

**Comment by richpl** [comment]
Sorry, I'm still getting a conflict with basicparser.py. Maybe I should make sure I submit PRs in order. This is getting tricky

**Comment by brickbots** [comment]
Hi @richpl!  Sorry we've been submitting all of these PR's, I'm not surprised they have some conflicts as there were a lot of changes across many files.

I'm happy to grab the latest master branch and rebase the FILE I/O and DATA changes from @RetiredWizard, and combine them with the remaining syntax tweaks and submit a single big PR.  I think once we get all the pieces of the vintage basic changes in one codebase the PR's will be smaller and flow more easily.

Let me know if anyone has any thoughts/concerns with me merging/resolving these all in one branch and doing a new PR.

**Comment by RetiredWizard** [comment]
The conflicts on my two PRs look easy enough, I'll just update the requests. I don't mind going through a couple iterations to get them done. Thanks @richpl!

**Comment by RetiredWizard** [comment]
okay, I tried to use the github resolve conflict but that caused github to spit out the entire basicparser module. I've reloaded basicparser and it appears to be conflict free now.

**Comment by RetiredWizard** [comment]
Well I seemed to have messed up this PR. I'm going to close it and then resubmit a new one. Sorry :(

**Pull request closed without merging**
